---
abstract: 'A cheap and easy way to enable CORS requests (cross origin resource sharing) for public APIs; configurability is on the TODO'
author:
  - 'Nour Sharabash <amirite@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  File::Spec::Functions: '0'
  File::Temp: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  List::Util: '0'
  Test::More: '0'
  perl: '5.006'
  strict: '0'
  version: '0'
  warnings: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.015, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojolicious-Plugin-CORS
no_index:
  directory:
    - t
  package:
    - DB
provides:
  Mojolicious::Plugin::CORS:
    file: lib/Mojolicious/Plugin/CORS.pm
    version: '0.01'
requires:
  Mojo::Base: '0'
  Mojolicious: '0'
  perl: '5.006'
resources:
  bugtracker: https://github.com/sharabash/mojolicious-plugin-cors/issues
  homepage: https://metacpan.org/release/Mojolicious-Plugin-CORS
  repository: git://github.com/sharabash/mojolicious-plugin-cors.git
version: '0.01'
x_authority: cpan:AMIRITE
x_contributors:
  - 'Nour Sharabash <nour.sharabash@gmail.com>'
